apiVersion: apps/v1
kind: Deployment
metadata:
  name: codesoft-app
  labels:
    app: codesoft-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codesoft-app
  template:
    metadata:
      labels:
        app: codesoft-app
    spec:
      containers:
      - name: codesoft-app
        image: 551529689545.dkr.ecr.us-east-1.amazonaws.com/codesoft:latest
        ports:
        - containerPort: 5000
        resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"


        env:
          - name: CODESOFT
            valueFrom:
              secretKeyRef:
                name: codesoft-secret
                key: CODESOFT

          - name: GUNICORN_WORKERS
            value: "1"

          - name: GUNICORN_TIMEOUT
            value: "120"

          # ðŸ”§ FIX 3: Allow slow model startup
        startupProbe:
            httpGet:
              path: /health
              port: 5000
            failureThreshold: 30
            periodSeconds: 5

        readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: codesoft-app-service
spec:
  type: LoadBalancer
  selector:
    app: codesoft-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000

